name: CI/CD Pipeline for ShoppingWeb Application
on:
  push:
    branches:
      - master
jobs:
  # [1] Compilación
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Compile Code
        run: mvn clean compile

  # [2] Ejecución de Pruebas Unitarias
  unit-tests:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run Unit Tests
        run: mvn test -Dtest=com.example.simplewebapp.ShoppingServiceTests

  # [3] Packaging
  package:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Package Application
        run: mvn install -DskipTests